name: flutter_cache_manager
description: Generic cache manager for flutter. Saves web files on the storages of the device and saves the cache info using sqflite.
version: 2.1.3
homepage: https://github.com/Baseflow/flutter_cache_manager

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  uuid: ^3.0.1
  http: ^0.13.1
  path: ^1.8.0
  sqflite: ^2.0.0+3
  pedantic: ^1.11.0
  clock: ^1.1.0
  file: ^6.1.0
  rxdart: ^0.26.0
  image: ^3.0.2
  collection: ^1.15.0-nullsafety.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.2
